# -*- coding: utf-8 -*-
"""MP_kelompok 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjV-tfxbKwk3mwBydt4iIX7txhY1PMp-
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("s3programmer/disease-diagnosis-dataset")

print("Path to dataset files:", path)

import pandas as pd

df = pd.read_csv(path + "/disease_diagnosis.csv")

df.info()

import pandas as pd
import numpy as np

# Combine all symptom columns into a single Series of lists
all_symptoms = df[['Symptom_1', 'Symptom_2', 'Symptom_3']].values.tolist()

# Flatten the list of lists and get unique symptoms
flat_list = [item for sublist in all_symptoms for item in sublist if pd.notna(item)]
unique_symptoms = list(set(flat_list))

# Create new columns for one-hot encoding
for symptom in unique_symptoms:
    df[symptom] = 0

# Populate the one-hot encoded columns
for index, row in df.iterrows():
    symptoms_in_row = [row['Symptom_1'], row['Symptom_2'], row['Symptom_3']]
    for symptom in symptoms_in_row:
        if pd.notna(symptom) and symptom in unique_symptoms:
            df.at[index, symptom] = 1

# Drop the original symptom columns if desired
# df = df.drop(['Symptom_1', 'Symptom_2', 'Symptom_3'], axis=1)

# Display the updated DataFrame with one-hot encoding
print(df.head())

import pandas as pd
# Perform one-hot encoding on the 'Diagnosis' column
diagnosis_one_hot = pd.get_dummies(df['Diagnosis'], prefix='Diagnosis')

# Convert the boolean values (True/False) to integers (1/0)
diagnosis_one_hot = diagnosis_one_hot.astype(int)

# Join the new one-hot encoded columns back to the original DataFrame
df = df.join(diagnosis_one_hot)

# Display the updated DataFrame
df.columns

import pandas as pd
# Perform one-hot encoding on the 'Treatment_Plan' column
treatment_plan_one_hot = pd.get_dummies(df['Treatment_Plan'], prefix='Treatment_Plan')

# Convert the boolean values (True/False) to integers (1/0)
treatment_plan_one_hot = treatment_plan_one_hot.astype(int)

# Join the new one-hot encoded columns back to the original DataFrame
df = df.join(treatment_plan_one_hot)

# Display the updated DataFrame
print(df.head())
df.columns

# prompt: want to do corr() so i need to pre process Blood_Pressure_mmHg column that has values such as '132/91' and '109/106' to columns systolic and average

import pandas as pd
# Function to extract systolic and calculate average blood pressure
def process_blood_pressure(bp_str):
    if isinstance(bp_str, str) and '/' in bp_str:
        try:
            systolic, diastolic = map(int, bp_str.split('/'))
            average = (systolic + diastolic) / 2
            return systolic, average
        except ValueError:
            return None, None  # Handle cases where conversion to int fails
    return None, None # Handle cases where format is not as expected

# Apply the function to create new columns
df[['Systolic_BP', 'Average_BP']] = df['Blood_Pressure_mmHg'].apply(lambda x: pd.Series(process_blood_pressure(x)))

# Display the updated DataFrame with new columns
print(df[['Blood_Pressure_mmHg', 'Systolic_BP', 'Average_BP']].head())

# clean the df of irrelevant columns
binary_cols = df.drop(columns=['Patient_ID', 'Age', 'Gender', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Blood_Pressure_mmHg', 'Diagnosis', 'Treatment_Plan', 'Severity'])

# Create a new DataFrame with only these columns
case_base = binary_cols.copy()

print(case_base.head())
case_base.columns

case_base.to_csv('/content/case_base.csv')

case_base.to_excel('/content/case_base.xlsx')

case_base.head().to_excel('/content/case_base_head.xlsx')

case_base.head(20).to_csv('/content/case_base_sampel.csv')

# Find columns that start with 'Treatment_Plan_'
Diagnosis_cols = [col for col in case_base.columns if col.startswith('Diagnosis_')]
# Select all columns except the Diagnosis columns
other_cols = [col for col in case_base.columns if col not in Diagnosis_cols]
# Calculate the correlation matrix between treatment plan columns and the rest
correlation_matrix = case_base[Diagnosis_cols].corrwith(case_base[other_cols])
print("Correlation between Treatment Plan columns and other columns:")
print(correlation_matrix)
# You can also calculate the full correlation matrix and then select the relevant part
full_correlation_matrix = case_base.corr()
# Select the correlation values between treatment plan columns and other columns
correlation_subset = full_correlation_matrix.loc[Diagnosis_cols, other_cols]
print("\nFull Correlation Matrix Subset (Treatment Plan vs Others):")
correlation_subset

correlation_subset.to_csv('/content/correlation_subset.csv')
print("Correlation subset saved to /content/correlation_subset.csv")

correlation_subset.to_excel('/content/correlation_subset.xlsx')

correlation_subset.head().to_csv('/content/correlation_subset_sampel.csv')

print("\nMemeriksa nilai kosong (NaN):")
print(df.isnull().sum())

print("\nMemeriksa nilai duplikat:")
print("Number of duplicate rows:", df.duplicated().sum())

features = ['Heart_Rate_bpm', 'Body_Temperature_C', 'Oxygen_Saturation_%',
       'Body ache', 'Headache', 'Shortness of breath', 'Cough', 'Fatigue',
       'Sore throat', 'Runny nose', 'Fever','Systolic_BP', 'Average_BP']

X = case_base[features].copy()
X.columns

symptoms = X.columns.tolist()
print(symptoms)

from sklearn.cluster import KMeans

# Handle potential NaN values by filling with 0 (or another suitable strategy)
X = X.fillna(0)

# Choose the number of clusters (you might need to experiment with this)
n_clusters = 5

# Initialize and fit the KMeans model
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
case_base['Cluster'] = kmeans.fit_predict(X)

# Display the first few rows with the new 'Cluster' column
print(case_base[['Cluster'] + symptoms].head())

# You can also look at the distribution of data within each cluster
print("\nCluster sizes:")
print(case_base['Cluster'].value_counts())

# To understand the characteristics of each cluster, you can aggregate the mean values of the features within each cluster
print("\nCluster centers:")
print(case_base.groupby('Cluster')[symptoms].mean())

print("number of columns:")
case_base.shape[1]

# import pandas as pd
# # Calculate total number of entries
# total_entries = len(df)

# # Define the list of symptom columns to calculate rarity for

# # Create an empty list to store rarity data
# rarity_data = []

# # Calculate rarity for each symptom column
# for col in symptoms:
#     # Ensure the column exists and contains numerical data suitable for sum
#     if col in case_base.columns and pd.api.types.is_numeric_dtype(case_base[col]):
#         # Count the number of entries with value 1 in the column
#         count_ones = case_base[col].sum()
#         # Calculate rarity value
#         rarity_value = (total_entries - count_ones) * 10 / total_entries
#         # Append symptom and rounded rarity value to the list
#         rarity_data.append({'Symptom': col, 'Rarity Value': int(round(rarity_value))})
#     else:
#         print(f"Warning: Column '{col}' not found or not numerical. Skipping.")

# # Create a DataFrame from the rarity data
# rarity_df = pd.DataFrame(rarity_data)

# # Display the rarity table
# print("\nRarity Value of Symptoms:")
# rarity_df

"""#case_base -> dataframase kasus lama
#kmeans -> model clustering yang sudah training
#rarity_df -> pembobotan fitur
"""

# new_case = pd.DataFrame({
#     'Fatigue'                         : [0],
#     'Body ache'                       : [0],
#     'Headache'                        : [0],
#     'Runny nose'                      : [0],
#     'Sore throat'                     : [1],
#     'Headache'                        : [1],
#     'Fever'                           : [1],
#     'Shortness of breath'             : [0],
#     'Cough'                           : [0],
#     'Heart_Rate_High'                 : [0],
#     'Body_Temperature_Fever (High)'   : [1],
#     'Body_Temperature_Fever (Mild)'   : [0],
#     'Blood_Pressure_High'             : [0],
#     'Blood_Pressure_Prehypertension'  : [0],
#     'Oxygen_Saturation_Mildly Low'    : [0]
#   })

# prompt: new_case entry with the following attributes as according to case_base features. 'Heart_Rate_bpm', 'Body_Temperature_C', 'Oxygen_Saturation_%',
#        'Body ache', 'Headache', 'Shortness of breath', 'Cough', 'Fatigue',
#        'Sore throat', 'Runny nose', 'Fever','Systolic_BP', 'Average_BP'

import pandas as pd
new_case = pd.DataFrame({
    'Heart_Rate_bpm': [75],
    'Body_Temperature_C': [38.5],
    'Oxygen_Saturation_%': [95],
    'Body ache': [1],
    'Headache': [1],
    'Shortness of breath': [0],
    'Cough': [0],
    'Fatigue': [1],
    'Sore throat': [1],
    'Runny nose': [0],
    'Fever': [1],
    'Systolic_BP': [125],
    'Average_BP': [85]
})

"""#RETRIEVE"""

# prompt: predict cluster for new_case by closest centroid k-means model already fitted for case_base before

# Make sure the columns of the new case match the order of the training data (X)
new_case = new_case[X.columns]

# Predict the cluster for the new case
predicted_cluster = kmeans.predict(new_case)
new_case["Cluster"] = predicted_cluster

# Display the predicted cluster
print(f"The new case is predicted to belong to cluster: {predicted_cluster[0]}")

# You can now access the characteristics of the predicted cluster from the aggregated means
predicted_cluster_characteristics = case_base.groupby('Cluster')[symptoms].mean().loc[predicted_cluster[0]]
print(f"\nCharacteristics of the predicted cluster ({predicted_cluster[0]}):")
print(predicted_cluster_characteristics)

# You could also find the case(s) in the original case_base that belong to this cluster
# cases_ in_predicted_cluster = case_base[case_base['Cluster'] == predicted_cluster[0]]
# print(f"\nCases in the predicted cluster ({predicted_cluster[0]}):")
# print(cases_in_predicted_cluster.head())

# new_case_weights = {}
# for feature, value in new_case.iloc[0].items():
#     if value == 1:
#         rarity_value = rarity_df[rarity_df['Symptom'] == feature]['Rarity Value'].iloc[0].item()
#         new_case_weights[feature] = rarity_value
#     else:
#         new_case_weights[feature] = 0

# print("\Bobot fitur kasus baru:")
# new_case_weights

# prompt: compare the values of new_case and values of entries for case_base to find the case in case_base most similar to new_case. calculate with neighbor similarity

import pandas as pd
def weighted_neighbor_similarity(case1, case2, weights):
    """
    Calculates the weighted neighbor similarity between two cases.

    Args:
        case1 (pd.Series): The first case (as a pandas Series).
        case2 (pd.Series): The second case (as a pandas Series).
        weights (dict): A dictionary where keys are feature names and values
                        are their weights.

    Returns:
        float: The weighted neighbor similarity score.
    """
    intersection = 0
    union = 0
    for feature in weights:
        weight = weights[feature]
        if case1[feature] == 1 and case2[feature] == 1:
            intersection += weight
        if case1[feature] == 1 or case2[feature] == 1:
            union += weight

    # Avoid division by zero if union is 0
    if union == 0:
        return 0
    return intersection / union

# Calculate weights based on rarity (or any other desired method)
# For simplicity, let's use a basic weight based on the feature's presence
# in the training data. You can replace this with your rarity calculation.
feature_weights = {}
for col in features:
  # Simple weight: 1 if present in at least one training case, 0 otherwise
  feature_weights[col] = 1 if case_base[col].sum() > 0 else 0

# Ensure weights are calculated for all relevant features
# You might want to use your rarity_df for a more sophisticated weighting
# For demonstration, let's use a simple equal weight for all features in `features`
feature_weights = {feature: 1 for feature in features}


# Initialize variables to store the best similarity and the most similar case
best_similarity = -1
most_similar_case_index = -1

# Iterate through each case in the case_base
for index, case_entry in case_base[features].iterrows():
    # Calculate the weighted neighbor similarity between the new case and the current case entry
    similarity = weighted_neighbor_similarity(new_case.iloc[0][features], case_entry, feature_weights)

    # Update the best similarity and the index of the most similar case if the current similarity is better
    if similarity > best_similarity:
        best_similarity = similarity
        most_similar_case_index = index

# Get the most similar case entry from the original DataFrame (or case_base)
most_similar_case = case_base.iloc[most_similar_case_index]

print(f"\nMost similar case found at index: {most_similar_case_index}")
print(f"Weighted Neighbor Similarity: {best_similarity:.4f}")
print("\nDetails of the most similar case:")
print(most_similar_case)

# You can also retrieve the original row from the 'df' DataFrame
# using the index if you need more columns than what's in case_base
original_most_similar_row = df.iloc[most_similar_case_index]
print("\nOriginal details from the full dataset:")
original_most_similar_row

# prompt: find most similar case in case_base (same cluster) to new_case with neighbor similarity by observing the VALUES of the columns

import numpy as np
from scipy.spatial.distance import euclidean

# Filter case_base to include only cases in the predicted cluster
cases_in_predicted_cluster = case_base[case_base['Cluster'] == predicted_cluster[0]].copy()

# Define a function to calculate similarity using inverse euclidean distance weighted by rarity
def weighted_inverse_euclidean_similarity(case1, case2, weights):
    """Calculates weighted inverse Euclidean similarity between two cases."""
    # Ensure both cases have the same columns and order as weights
    case1_aligned = case1[weights.keys()]
    case2_aligned = case2[weights.keys()]

    # Calculate weighted squared differences
    weighted_sq_diff = sum((weights[col] * (case1_aligned[col] - case2_aligned[col]))**2 for col in weights.keys())

    # Calculate weighted Euclidean distance
    weighted_dist = np.sqrt(weighted_sq_diff)

    # Calculate inverse Euclidean distance (add a small constant to avoid division by zero)
    similarity = 1 / (1 + weighted_dist)
    return similarity

# Calculate similarity of the new case with all cases in the predicted cluster
similarities = cases_in_predicted_cluster.apply(
    lambda row: weighted_inverse_euclidean_similarity(new_case.iloc[0], row, new_case_weights),
    axis=1
)

# Find the index of the case with the highest similarity
most_similar_case_index = similarities.idxmax()

# Retrieve the most similar case from the original case_base using the index
most_similar_case = case_base.loc[most_similar_case_index]

print("\nMost similar case in the same cluster:")
print(most_similar_case)

print(f"\nSimilarity score with the most similar case: {similarities.max()}")

# You can now access the original data for the most similar case from the full df
original_most_similar_data = df.loc[most_similar_case_index]
print("\nOriginal data for the most similar case:")
print(original_most_similar_data[['Diagnosis', 'Treatment_Plan', 'Severity']])

def calculate_weighted_similarity(case1, case2, weights):
    similarity = 0
    total_weight = sum(new_case.values())
    # total_weight = sum(weights.values())
    if total_weight == 0:  # Avoid division by zero if all weights are zero
        return 0

    for feature in case1.keys():
        # Ensure features exist in both cases
        if feature in case1 and feature in case2:
            # Simple matching for binary features (0 or 1)
            if case1[feature] == case2[feature]:
                similarity += weights[feature]
    return similarity / total_weight

# Filter old cases that belong to the predicted cluster
old_cases_in_predicted_cluster = case_base[case_base['Cluster'] == predicted_cluster[0]].copy()

# Calculate weighted similarity for each old case in the predicted cluster
similarities = []
for index, row in old_cases_in_predicted_cluster.iterrows():
    similarity = calculate_weighted_similarity(new_case.iloc[0], row, new_case_weights)
    similarities.append((index, similarity))

# Find the case with the highest similarity
most_similar_case_index, max_similarity = max(similarities, key=lambda item: item[1])

# Get the most similar case from the original case_base
most_similar_case = case_base.loc[most_similar_case_index]

print(f"\nMost similar case to the new case (within predicted cluster {predicted_cluster[0]}):")
print(f"Index in case_base: {most_similar_case_index}")
print(f"Weighted Similarity: {max_similarity:.4f}")
print("\nDetails of the most similar case:")
most_similar_case

"""### most_similar_case -> barisan kasus lama paling mirip
### most_similar_case_index -> index kasus lama paling mirip

#REUSE
"""

diagnosis_cols = [col for col in most_similar_case.index if col.startswith('Diagnosis_')]
treatment_plan_cols = [col for col in most_similar_case.index if col.startswith('Treatment_Plan_')]

for col in diagnosis_cols:
  new_case[col] = most_similar_case[col]

for col in treatment_plan_cols:
  new_case[col] = most_similar_case[col]

print(new_case)

"""# REVISE"""

print(symptoms)

from sklearn.naive_bayes import GaussianNB

X_nb = case_base[symptoms]

treatment_plan_models = {} #menampung model untuk setiap jenis perawatan

for treatment_col in treatment_plan_cols:
  y_nb = case_base[treatment_col]

  nb_model = GaussianNB()
  nb_model.fit(X_nb, y_nb)
  treatment_plan_models[treatment_col] = nb_model

new_case_symptoms = new_case[symptoms]

treatment_plan_probabilities = {}#menampung nilai kepercayaan prediksi model setiap jenis perawatan
for treatment_col, model in treatment_plan_models.items():
  treatment_plan_probabilities[treatment_col] = model.predict_proba(new_case_symptoms)[:, 1][0]

print("\nNilai kepercayaan Naive Bayes kasus baru untuk setiap jenis perawatan :")
print(treatment_plan_probabilities)

best_treatment_plan_col = max(treatment_plan_probabilities, key=treatment_plan_probabilities.get)
highest_probability = treatment_plan_probabilities[best_treatment_plan_col]

print(f"\nBest Treatment Plan based on Naive Bayes probability: {best_treatment_plan_col}")
print(f"Highest Probability: {highest_probability:.4f}")

if best_treatment_plan_col in new_case.columns:
    new_case[best_treatment_plan_col] = 1 # Set the recommended treatment plan to 1
else:
    print(f"Warning: Recommended treatment plan '{best_treatment_plan_col}' not found in new_case columns.")


print("\nNew case DataFrame after Naive Bayes recommendation:")
new_case[treatment_plan_cols]

case_base = pd.concat([case_base, new_case], ignore_index=True)
print("\nKasus baru di indeks terakhir case_base:")
print(case_base.tail())

print(features)

